import load from "~/loadModules";

export default {
  namespaced: true,
  state: {
    suburbs: [
      { postcode: "4000", district: "Brisbane, Spring Hill" },
      { postcode: "4001", district: "Brisbane" },
      { postcode: "4002", district: "City East, Wintergarden" },
      { postcode: "4003", district: "Brisbane" },
      { postcode: "4004", district: "Brisbane" },
      { postcode: "4005", district: "New Farm" },
      { postcode: "4006", district: "Bowen Hills, Fortitude Valley, Herston, Newstead" },
      { postcode: "4007", district: "Ascot, Hamilton" },
      { postcode: "4008", district: "Pinkenba" },
      { postcode: "4009", district: "Eagle Farm" },
      { postcode: "4010", district: "Albion" },
      { postcode: "4011", district: "Clayfield, Hendra" },
      { postcode: "4012", district: "Nundah, Toombul, Wavell Heights, Wavell Heights North" },
      { postcode: "4013", district: "Northgate" },
      { postcode: "4014", district: "Banyo, Nudgee, Nudgee Beach, Virginia" },
      { postcode: "4017", district: "Bracken Ridge, Brighton, Deagon, Sandgate, Shorncliffe" },
      { postcode: "4018", district: "Fitzgibbon, Taigum" },
      { postcode: "4019", district: "Clontarf, Margate, Margate Beach, Woody Point" },
      { postcode: "4020", district: "Redcliffe, Scarborough" },
      { postcode: "4021", district: "Kippa-ring" },
      { postcode: "4022", district: "Rothwell" },
      { postcode: "4025", district: "Bulwer, Cape Moreton, Cowan Cowan, Kooringal, Tangalooma" },
      { postcode: "4029", district: "Royal Brisbane Hospital" },
      { postcode: "4030", district: "Lutwyche, Windsor, Wooloowin" },
      { postcode: "4031", district: "Gordon Park, Kedron" },
      { postcode: "4032", district: "Chermside, Chermside West" },
      { postcode: "4034", district: "Aspley, Boondall, Carseldine, Geebung, Zillmere" },
      { postcode: "4035", district: "Albany Creek, Bridgeman Downs" },
      { postcode: "4036", district: "Bald Hills" },
      { postcode: "4037", district: "Eatons Hill" },
      { postcode: "4051", district: "Alderley, Enoggera, Gaythorne, Grange, Newmarket, Wilston" },
      { postcode: "4053", district: "Brookside Centre, Everton Hills, Everton Park, Mcdowall, Mitchelton, Stafford, Stafford Heights" },
      { postcode: "4054", district: "Arana Hills, Keperra" },
      { postcode: "4055", district: "Bunya, Ferny Grove, Ferny Hills, Upper Kedron" },
      { postcode: "4059", district: "Kelvin Grove, Red Hill" },
      { postcode: "4060", district: "Ashgrove" },
      { postcode: "4061", district: "The Gap" },
      { postcode: "4064", district: "Milton, Paddington" },
      { postcode: "4065", district: "Bardon" },
      { postcode: "4066", district: "Auchenflower, Mount Coot-tha, Toowong" },
      { postcode: "4067", district: "St Lucia" },
      { postcode: "4068", district: "Chelmer, Indooroopilly, Taringa" },
      { postcode: "4069", district: "Brookfield, Chapel Hill, Fig Tree Pocket, Kenmore, Kenmore Hills, Pinjarra Hills, Pullenvale, Upper Brookfield" },
      { postcode: "4070", district: "Anstead, Bellbowrie, Moggill" },
      { postcode: "4072", district: "University Of Queensland" },
      { postcode: "4073", district: "Seventeen Mile Rocks, Sinnamon Park" },
      { postcode: "4074", district: "Jamboree Heights, Jindalee, Middle Park, Mount Ommaney, Riverhills, Sumner, Westlake" },
      { postcode: "4075", district: "Corinda, Graceville, Graceville East, Oxley, Sherwood" },
      { postcode: "4076", district: "Darra, Wacol" },
      { postcode: "4077", district: "Doolandella, Durack, Inala, Richlands" },
      { postcode: "4078", district: "Ellen Grove, Forest Lake" },
      { postcode: "4101", district: "Highgate Hill, South Brisbane, West End" },
      { postcode: "4102", district: "Buranda, Dutton Park, Woolloongabba" },
      { postcode: "4103", district: "Annerley, Fairfield" },
      { postcode: "4104", district: "Yeronga" },
      { postcode: "4105", district: "Moorooka, Tennyson, Yeerongpilly" },
      { postcode: "4106", district: "Rocklea" },
      { postcode: "4107", district: "Salisbury" },
      { postcode: "4108", district: "Archerfield, Coopers Plains" },
      { postcode: "4109", district: "Macgregor, Robertson, Sunnybank, Sunnybank Hills" },
      { postcode: "4110", district: "Acacia Ridge, Heathwood, Larapinta, Pallara, Willawong" },
      { postcode: "4111", district: "Nathan" },
      { postcode: "4112", district: "Kuraby" },
      { postcode: "4113", district: "Eight Mile Plains, Runcorn" },
      { postcode: "4114", district: "Kingston, Logan Central, Woodridge" },
      { postcode: "4115", district: "Algester, Parkinson" },
      { postcode: "4116", district: "Calamvale, Drewvale, Stretton" },
      { postcode: "4117", district: "Berrinba, Karawatha" },
      { postcode: "4118", district: "Browns Plains, Forestdale, Heritage Park, Hillcrest, Regents Park" },
      { postcode: "4119", district: "Underwood" },
      { postcode: "4120", district: "Greenslopes, Stones Corner" },
      { postcode: "4121", district: "Holland Park, Holland Park West, Tarragindi, Wellers Hill" },
      { postcode: "4122", district: "Mansfield, Mount Gravatt, Mount Gravatt East, Upper Mount Gravatt, Wishart" },
      { postcode: "4123", district: "Rochedale, Rochedale South" },
      { postcode: "4124", district: "Boronia Heights, Greenbank" },
      { postcode: "4125", district: "Munruben, Park Ridge" },
      { postcode: "4127", district: "Daisy Hill, Priestdale, Slacks Creek, Springwood" },
      { postcode: "4128", district: "Shailer Park, Tanah Merah" },
      { postcode: "4129", district: "Loganholme" },
      { postcode: "4130", district: "Carbrook, Cornubia" },
      { postcode: "4131", district: "Loganlea, Meadowbrook" },
      { postcode: "4132", district: "Crestmead, Marsden" },
      { postcode: "4133", district: "Chambers Flat, Logan Reserve, Waterford, Waterford West" },
      { postcode: "4151", district: "Coorparoo" },
      { postcode: "4152", district: "Camp Hill, Carina, Carina Heights, Carindale" },
      { postcode: "4153", district: "Belmont" },
      { postcode: "4154", district: "Gumdale, Ransome, Wakerley" },
      { postcode: "4155", district: "Chandler" },
      { postcode: "4156", district: "Burbank, Mackenzie" },
      { postcode: "4157", district: "Capalaba, Capalaba West, Sheldon" },
      { postcode: "4158", district: "Thorneside" },
      { postcode: "4159", district: "Birkdale" },
      { postcode: "4160", district: "Ormiston, Wellington Point" },
      { postcode: "4161", district: "Alexandra Hills" },
      { postcode: "4163", district: "Cleveland" },
      { postcode: "4164", district: "Thornlands" },
      { postcode: "4165", district: "Mount Cotton, Redland Bay, Victoria Point" },
      { postcode: "4169", district: "East Brisbane, Kangaroo Point" },
      { postcode: "4170", district: "Cannon Hill, Morningside, Norman Park, Seven Hills" },
      { postcode: "4171", district: "Balmoral, Bulimba, Hawthorne" },
      { postcode: "4172", district: "Murarrie" },
      { postcode: "4173", district: "Tingalpa" },
      { postcode: "4174", district: "Hemmant" },
      { postcode: "4178", district: "Lytton, Port Of Brisbane, Wynnum, Wynnum North, Wynnum West" },
      { postcode: "4179", district: "Lota, Manly, Manly West" },
      { postcode: "4183", district: "Amity, Dunwich, Point Lookout" },
      { postcode: "4184", district: "Coochiemudlo Island, Karragarra Island, Lamb Island, Macleay Island, Peel Island, Russell Island" },
      { postcode: "4205", district: "Bethania" },
      { postcode: "4207", district: "Alberton, Bahrs Scrub, Bannockburn, Beenleigh, Belivah, Buccan, Cedar Creek, Eagleby, Edens Landing, Holmview, Logan Village, Luscombe, Mount Warren Park, Stapylton, Steiglitz, Windaroo, Wolffdene, Woongoolba, Yatala" },
      { postcode: "4208", district: "Gilberton, Jacobs Well, Kingsholme, Norwell, Ormeau, Ormeau Hills" },
      { postcode: "4209", district: "Coomera, Pimpama, Upper Coomera, Willow Vale" },
      { postcode: "4210", district: "Guanaba, Maudsland, Oxenford, Studio Village, Wongawallan" },
      { postcode: "4211", district: "Advancetown, Beechmont, Carrara, Clagiraba, Gaven, Gilston, Highland Park, Mount Nathan, Natural Bridge, Nerang, Numinbah Valley, Pacific Pines" },
      { postcode: "4212", district: "Helensvale, Helensvale Town Centre, Hope Island, Sanctuary Cove" },
      { postcode: "4213", district: "Austinville, Bonogin, Mudgeeraba, Springbrook, Tallai, Worongary" },
      { postcode: "4214", district: "Arundel, Ashmore, Molendinar, Parkwood" },
      { postcode: "4215", district: "Chirn Park, Labrador, Southport" },
      { postcode: "4216", district: "Biggera Waters, Coombabah, Hollywell, Paradise Point, Runaway Bay, South Stradbroke" },
      { postcode: "4217", district: "Benowa, Bundall, Chevron Island, Isle Of Capri, Main Beach, Surfers Paradise" },
      { postcode: "4218", district: "Broadbeach, Broadbeach Waters, Mermaid Beach, Mermaid Waters, Nobby Beach, Pacific Fair" },
      { postcode: "4219", district: "Burleigh" },
      { postcode: "4220", district: "Burleigh Heads, Burleigh Waters, Miami" },
      { postcode: "4221", district: "Elanora, Palm Beach" },
      { postcode: "4223", district: "Currumbin, Currumbin Valley, Currumbin Waters" },
      { postcode: "4224", district: "Tugun" },
      { postcode: "4225", district: "Bilinga, Coolangatta" },
      { postcode: "4226", district: "Clear Island Waters, Merrimac, Robina" },
      { postcode: "4227", district: "Reedy Creek, Varsity Lakes" },
      { postcode: "4228", district: "Tallebudgera, Tallebudgera Valley" },
      { postcode: "4229", district: "Bond University" },
      { postcode: "4230", district: "Robina Town Centre" },
      { postcode: "4270", district: "Tamborine" },
      { postcode: "4271", district: "Eagle Heights" },
      { postcode: "4272", district: "Mount Tamborine, North Tamborine, Tamborine Mountain" },
      { postcode: "4275", district: "Canungra, Lamington National Park, Witheren, Wonglepong" },
      { postcode: "4280", district: "Jimboomba" },
      { postcode: "4285", district: "Beaudesert, Cedar Grove, Cedar Vale, Kooralbyn" },
      { postcode: "4287", district: "Palen Creek, Rathdowney" },
      { postcode: "4300", district: "Augustine Heights, Bellbird Park, Brookwater, Camira, Carole Park, Gailes, Goodna, Springfield, Springfield Lakes" },
      { postcode: "4301", district: "Collingwood Park, Redbank, Redbank Plains" },
      { postcode: "4303", district: "Dinmore, New Chum, Riverview" },
      { postcode: "4304", district: "Blackstone, Booval, Bundamba, Ebbw Vale, North Booval, Silkstone" },
      { postcode: "4305", district: "Basin Pocket, Brassall, Bremer, Churchill, Coalfalls, East Ipswich, Eastern Heights, Flinders View, Ipswich, Leichhardt, Limestone Ridges, Moores Pocket, Newtown, North Ipswich, North Tivoli, One Mile, Raceview, Sadliers Crossing, Tivoli, West Ipswich, Woodend, Wulkuraka, Yamanto" },
      { postcode: "4307", district: "Harrisville" },
      { postcode: "4309", district: "Aratula, Frazerview, Kalbar, Washpool" },
      { postcode: "4310", district: "Boonah, Roadvale" },
      { postcode: "4311", district: "Buaraba South, Churchable, Coominya, Lockyer Waters, Lowood, Minden, Patrick Estate, Wivenhoe Hill" },
      { postcode: "4312", district: "Bryden, Caboonbah, Crossdale, Esk, Glen Esk, Moombra, Mount Byron, Redbank Creek, Somerset Dam" },
      { postcode: "4313", district: "Braemore, Cooeeimbardi, Fulham, Lower Cressbrook, Ottaba, Scrub Creek, Toogoolawah, Yimbun" },
      { postcode: "4340", district: "Grandchester, Lanefield, Lower Mount Walker, Merryvale, Mount Mort, Mount Walker West, Rosewood, Tallegalla, The Bluff" },
      { postcode: "4341", district: "Kensington Grove, Laidley, Laidley Creek West, Laidley Heights, Laidley North, Plainland, Townson" },
      { postcode: "4342", district: "Forest Hill, Glen Cairn, Glenore Grove, Lynford" },
      { postcode: "4343", district: "Adare, Black Duck Creek, Caffey, College View, East Haldon, Fordsdale, Gatton, Ingoldsby, Junction View, Lake Clarendon, Lawes, Lefthand Branch, Lower Tenthill, Morton Vale, Mount Sylvia, Placid Hills, Ringwood, Rockside, Ropeley, Spring Creek, Upper Tenthill, Vinegar Hill, Woodbine, Woodlands" },
      { postcode: "4344", district: "Carpendale, Egypt, Flagstone Creek, Helidon, Helidon Spa, Lilydale, Lockyer, Rockmount, Seventeen Mile, Silver Ridge, Stockyard, Upper Flagstone" },
      { postcode: "4345", district: "Gatton College" },
      { postcode: "4346", district: "Marburg" },
      { postcode: "4347", district: "Grantham, Ma Ma Creek, Mount Whitestone, Veradilla, Winwill" },
      { postcode: "4350", district: "Athol, Centenary Heights, Cranley, Darling Heights, Drayton, East Toowoomba, Finnie, Glenvale, Harlaxton, Harristown, Kearneys Spring, Middle Ridge, Mount Kynoch, Mount Lofty, Mount Rascal, Newtown, North Toowoomba, Northlands, Prince Henry Heights, Rangeville, Redwood, Rockville, South Toowoomba, Southtown, Toowoomba, Toowoomba East, Toowoomba South, Toowoomba West, Top Camp, Wellcamp, Westbrook, Wilsonton, Wilsonton Heights, Wyalla Plaza" },
      { postcode: "4353", district: "Bergen, East Cooyar, Haden" },
      { postcode: "4354", district: "Douglas, Goombungee" },
      { postcode: "4355", district: "Crows Nest, Glenaven, Pierces Creek, The Bluff" },
      { postcode: "4356", district: "Bongeen, Broxburn, Evanslea, Irongate, Kincora, Linthorpe, Motley, Mount Tyson, North Branch, Norwin, Pittsworth, Purrawunda, Rossvale, Scrubby Mountain, Springside, St Helens, Stoneleigh, Yarranlea" },
      { postcode: "4357", district: "Bringalily, Bulli Creek, Canning Creek, Captains Mountain, Clontarf, Condamine Farms, Cypress Gardens, Domville, Forest Ridge, Grays Gate, Kooroongarra, Lavelle, Lemontree, Millmerran, Millmerran Downs, Millmerran Woods, Millwood, Mount Emlyn, Punchs Creek, Rocky Creek, Stonehenge, The Pines, Turallin, Wattle Ridge, Western Creek, Woondul" },
      { postcode: "4358", district: "Cambooya, Felton, Felton South, Vale View" },
      { postcode: "4359", district: "Budgee, Greenmount, Greenmount East, West Haldon" },
      { postcode: "4360", district: "Nobby" },
      { postcode: "4361", district: "Clifton, Ellangowan, Elphinstone, Headington Hill, Kings Creek, Manapouri, Missen Flat, Mount Molar, Nevilton, Ryeford, Sandy Camp, Spring Creek, Victoria Hill" },
      { postcode: "4362", district: "Allora, Deuchar, Goomburra, Mount Marshall" },
      { postcode: "4363", district: "Southbrook" },
      { postcode: "4364", district: "Brookstead" },
      { postcode: "4365", district: "Leyburn" },
      { postcode: "4370", district: "Maryvale, Warwick" },
      { postcode: "4371", district: "Emu Vale, Yangan" },
      { postcode: "4372", district: "Tannymorel" },
      { postcode: "4373", district: "Killarney" },
      { postcode: "4374", district: "Dalveen" },
      { postcode: "4375", district: "Cottonvale" },
      { postcode: "4376", district: "Thulimbah" },
      { postcode: "4377", district: "The Summit" },
      { postcode: "4378", district: "Applethorpe" },
      { postcode: "4380", district: "Kyoomba, Stanthorpe" },
      { postcode: "4381", district: "Glen Aplin" },
      { postcode: "4382", district: "Ballandean" },
      { postcode: "4383", district: "Wallangarra" },
      { postcode: "4384", district: "Limevale" },
      { postcode: "4385", district: "Beebo, Bonshaw, Glenarbon, Maidenhead, Riverton, Silver Spur, Smithlea, Texas, Watsons Crossing" },
      { postcode: "4387", district: "Brush Creek, Bybera, Coolmunda, Greenup, Inglewood, Mosquito Creek, Terrica, Warroo, Whetstone" },
      { postcode: "4388", district: "Kurumbul, Yelarbon" },
      { postcode: "4390", district: "Billa Billa, Calingunee, Callandoon, Goodar, Goondiwindi, Kindon, Lundavra, Wondalli, Wyaga, Yagaburne" },
      { postcode: "4400", district: "Kingsthorpe" },
      { postcode: "4401", district: "Acland, Balgowan, Boodua, Devon Park, Greenwood, Highland Plains, Kelvinhaugh, Mount Irving, Muldu, Oakey, Rosalie Plains, Sabine, Silverleigh, Yargullen" },
      { postcode: "4402", district: "Cooyar, Kooralgin" },
      { postcode: "4403", district: "Brymaroo, Jondaryan, Malu, Mount Moriah, Quinalow, West Prairie" },
      { postcode: "4404", district: "Bowenville, Formartin, Irvingdale, Wainui" },
      { postcode: "4405", district: "Bunya Mountains, Dalby, Grassdale, Tipton" },
      { postcode: "4406", district: "Boondandilla, Hannaford, Jimbour, Kaimkillenbun, Kogan, Macalister, Moonie, The Gums, Weir River" },
      { postcode: "4407", district: "Cattle Creek, Cecil Plains, Dunmore, Nangwee" },
      { postcode: "4408", district: "Bell" },
      { postcode: "4410", district: "Jandowae" },
      { postcode: "4411", district: "Warra" },
      { postcode: "4412", district: "Brigalow" },
      { postcode: "4413", district: "Chinchilla, Hopeland, Wieambilla" },
      { postcode: "4415", district: "Gurulmundi, Hookswood, Kowguran, Miles, Myall Park, Pelham" },
      { postcode: "4416", district: "Barramornie, Condamine, Moraby, Nangram, Pine Hills, Sunnyside, Yulabilla" },
      { postcode: "4417", district: "Surat" },
      { postcode: "4418", district: "Guluguba" },
      { postcode: "4419", district: "Cockatoo, Grosmont, Wandoan" },
      { postcode: "4420", district: "Broadmere, Coorada, Ghinghinda, Glenhaughton, Gwambegwine, Hornet Bank, Peek-a-doo, Taroom" },
      { postcode: "4421", district: "Goranba, Tara" },
      { postcode: "4422", district: "Meandarra" },
      { postcode: "4423", district: "Glenmorgan" },
      { postcode: "4424", district: "Drillham, Drillham South, Glenaubyn" },
      { postcode: "4425", district: "Dulacca" },
      { postcode: "4426", district: "Jackson, Jackson North, Jackson South" },
      { postcode: "4427", district: "Yuleba, Yuleba North, Yuleba South" },
      { postcode: "4428", district: "Pickanjinnie, Wallumbilla, Wallumbilla North, Wallumbilla South" },
      { postcode: "4454", district: "Baffle West, Beilba, Durham Downs, Highland Plains, Hutton Creek, Injune, Mount Hutton, Pony Hills, Simmie, Upper Dawson, Westgrove" },
      { postcode: "4455", district: "Blythdale, Bungeworgorai, Bungil, Bymount, Cornwall, Dargal Road, Eumamurrin, Euthulla, Gunnewin, Hodgson, Mooga, Mount Abundance, Mount Bindango, Orallo, Orange Hill, Roma, Tingun" },
      { postcode: "4461", district: "Muckadilla" },
      { postcode: "4462", district: "Amby" },
      { postcode: "4465", district: "Mitchell" },
      { postcode: "4467", district: "Mungallala" },
      { postcode: "4468", district: "Morven" },
      { postcode: "4470", district: "Charleville" },
      { postcode: "4471", district: "Claverton" },
      { postcode: "4472", district: "Central West	Blackall, Mount Enniskillen" },
      { postcode: "4474", district: "Adavale" },
      { postcode: "4475", district: "Cheepie" },
      { postcode: "4477", district: "Augathella" },
      { postcode: "4478", district: "Bayrick, Caldervale, Lansdowne, Lumeah, Macfarlane, Minnie Downs, Scrubby Creek, Tambo, Windeyer, Yandarlo" },
      { postcode: "4479", district: "Cooladdi" },
      { postcode: "4480", district: "Eromanga, Quilpie" },
      { postcode: "4481", district: "Central West	Tanbar, Windorah" },
      { postcode: "4482", district: "Central West	Birdsville" },
      { postcode: "4486", district: "Dirranbandi, Hebel" },
      { postcode: "4487", district: "St George" },
      { postcode: "4488", district: "Bollon, Nebine" },
      { postcode: "4489", district: "Wyandra" },
      { postcode: "4490", district: "Barringun, Coongoola, Cunnamulla, Cuttaburra, Humeburn, Jobs Gate, Linden, Noorama, Tuen, Widgeegoara, Yowah" },
      { postcode: "4491", district: "Eulo" },
      { postcode: "4492", district: "Thargomindah" },
      { postcode: "4493", district: "Hungerford" },
      { postcode: "4494", district: "Bungunya, North Bungunya, Tarawera" },
      { postcode: "4496", district: "North Talwood, South Talwood, Talwood" },
      { postcode: "4497", district: "Daymar, Thallon, Weengallon" },
      { postcode: "4498", district: "Kioma, Toobeah" },
      { postcode: "4500", district: "Bray Park, Brendale, Cashmere, Clear Mountain, Joyner, Strathpine, Warner" },
      { postcode: "4501", district: "Lawnton" },
      { postcode: "4502", district: "Petrie" },
      { postcode: "4503", district: "Dakabin, Griffin, Kallangur, Kurwongbah, Murrumba Downs, Whiteside" },
      { postcode: "4504", district: "Narangba" },
      { postcode: "4505", district: "Burpengary" },
      { postcode: "4506", district: "Morayfield" },
      { postcode: "4507", district: "Banksia Beach, Bellara, Bongaree, Bribie Island, Bribie Island North, Welsby, White Patch, Woorim" },
      { postcode: "4508", district: "Deception Bay" },
      { postcode: "4509", district: "Mango Hill, North Lakes" },
      { postcode: "4510", district: "Beachmere, Caboolture, Caboolture South, Donnybrook, Toorbul" },
      { postcode: "4511", district: "Godwin Beach, Ningi, Sandstone Point" },
      { postcode: "4512", district: "Bracalba, Wamuran, Wamuran Basin" },
      { postcode: "4514", district: "Commissioners Flat, D Aguilar, Mount Archer, Mount Delaney, Stony Creek, Woodford" },
      { postcode: "4515", district: "Hazeldean, Jimna, Kilcoy, Monsildale" },
      { postcode: "4516", district: "Elimbah" },
      { postcode: "4517", district: "Beerburrum" },
      { postcode: "4518", district: "Glass House Mountains" },
      { postcode: "4519", district: "Beerwah, Coochin Creek, Crohamhurst, Peachester" },
      { postcode: "4520", district: "Armstrong Creek, Camp Mountain, Cedar Creek, Closeburn, Draper, Enoggera Reservoir, Highvale, Jollys Lookout, Kobble Creek, Mount Glorious, Mount Nebo, Samford, Mount Samson, Samford, Samsonvale, Wights Mountain, Yugar" },
      { postcode: "4521", district: "Dayboro, King Scrub, Laceys Creek, Mount Mee, Mount Pleasant, Ocean View, Rush Creek" },
      { postcode: "4550", district: "Landsborough" },
      { postcode: "4551", district: "Aroona, Battery Hill, Bells Creek, Caloundra, Caloundra West, Currimundi, Dicky Beach, Golden Beach, Kings Beach, Little Mountain, Moffat Beach, Pelican Waters, Shelly Beach" },
      { postcode: "4552", district: "Balmoral Ridge, Booroobin, Cambroon, Conondale, Curramore, Elaman Creek, Harper Creek, Maleny, North Maleny, Wootha" },
      { postcode: "4553", district: "Diamond Valley, Mooloolah, Palmview" },
      { postcode: "4554", district: "Eudlo, Ilkley" },
      { postcode: "4555", district: "Hunchy, Palmwoods" },
      { postcode: "4556", district: "Buderim, Kunda Park, Sippy Downs, Tanawha" },
      { postcode: "4557", district: "Mooloolaba, Mountain Creek" },
      { postcode: "4558", district: "Cotton Tree, Maroochydore, Sunshine Plaza" },
      { postcode: "4559", district: "Diddillibah, Kiels Mountain, Woombye" },
      { postcode: "4560", district: "Bli Bli, Dulong, Mapleton, Montville, Nambour, Perwillowen" },
      { postcode: "4561", district: "Maroochy River, Yandina" },
      { postcode: "4562", district: "Eumundi" },
      { postcode: "4563", district: "Cooroy, Cooroy Mountain, Lake Macdonald, Tinbeerwah" },
      { postcode: "4564", district: "Marcoola, Mudjimba, Pacific Paradise, Twin Waters" },
      { postcode: "4565", district: "Boreen Point, Cooroibah, Cootharaba, Noosa North Shore, Ringtail Creek, Tewantin" },
      { postcode: "4566", district: "Noosaville" },
      { postcode: "4567", district: "Castaways Beach, Noosa Heads, Sunrise Beach, Sunshine Beach" },
      { postcode: "4568", district: "Federal, Pinbarren, Pomona" },
      { postcode: "4569", district: "Cooran" },
      { postcode: "4571", district: "Kin Kin" },
      { postcode: "4572", district: "Alexandra Headland" },
      { postcode: "4573", district: "Coolum Beach, Marcus Beach, Mount Coolum, Peregian Beach, Peregian Springs, Yaroomba" },
      { postcode: "4574", district: "Kenilworth, Moy Pocket" },
      { postcode: "4575", district: "Birtinya, Bokarina, Buddina, Minyama, Parrearra, Warana, Wurtulla" },
      { postcode: "4580", district: "Cooloola, Cooloola Cove, Tin Can Bay" },
      { postcode: "4581", district: "Eurong, Inskip, Rainbow Beach" },
      { postcode: "4600", district: "Black Snake, Kilkivan, Mudlo, Oakview" },
      { postcode: "4601", district: "Barambah, Boonara, Booubyjan, Goomeri, Goomeribong, Kinbombi, Manumbar, Tansey, Wrattens Forest" },
      { postcode: "4605", district: "Barlil, Cherbourg, Cloyna, Cobbs Hill, Glenrock, Kitoba, Merlwood, Moffatdale, Moondooner, Murgon, Oakdale, Redgate, Silverleaf, Sunny Nook, Tablelands, Warnung, Wooroonden" },
      { postcode: "4606", district: "Chelmsford, Fairdale, Leafdale, Mount Mceuen, Mp Creek, Wheatlands, Wondai" },
      { postcode: "4608", district: "Charlestown, Tingoora, Wilkesdale, Wooroolin" },
      { postcode: "4610", district: "Alice Creek, Ballogie, Benair, Booie, Boyneside, Chahpingah, Coolabunia, Corndale, Dangore, Durong, Durong South, Goodger, Gordonbrook, Haly Creek, Hodgleigh, Inverlaw, Ironpot, Kingaroy, Kumbia, Mannuem, Taabinga, Wattle Grove" },
      { postcode: "4611", district: "Marshlands, Mondure" },
      { postcode: "4612", district: "Hivesville, Kawl Kawl, Keysland, Stonelands, Wigton" },
      { postcode: "4613", district: "Abbeywood, Boondooma, Coverty, Melrose, Okeden, Proston" },
      { postcode: "4614", district: "Neumgna, Upper Yarraman, Yarraman" },
      { postcode: "4615", district: "Barker Creek Flat, Bullcamp, East Nanango, Glan Devon, Johnstown, Kunioon, Maidenwell, Nanango, Pimpimbudgee, Runnymede, Sandy Ridges, South East Nanango, Tarong, Wattle Camp, Wengenville, Wyalla" },
      { postcode: "4620", district: "Brooweena, Doongul, Gigoomgan, Glenbar, Gungaloon, Malarga, North Aramara, Teebar, Woocoo" },
      { postcode: "4621", district: "Biggenden, Boompa, Coringa, Degilbo, Didcot, Golden Fleece, Wateranga, Woowoonga" },
      { postcode: "4625", district: "Aranbanga, Ban Ban, Ban Ban Springs, Barlyne, Bon Accord, Branch Creek, Campbell Creek, Deep Creek, Dirnbir, Dundarrah, Gayndah, Ginoondan, Harriet, Humphery, Ideraway, Mingo, Mount Debateable, Mount Lawless, Penwhaupell, Pile Gully, Reids Creek, Stockhaven, The Limits, Toondahra, Wahoon, Wetheron, Wilson Valley, Woodmillar, Yenda" },
      { postcode: "4626", district: "Beeron, Boynewood, Brovinia, Cattle Creek, Coonambula, Derri Derra, Dykehead, Glenrae, Hawkwood, Monogorilby, Mundowran, Mundubbera, Old Cooranga, Philpott, Riverleigh" },
      { postcode: "4627", district: "Abercorn, Ceratodus, Cheltenham, Cynthia, Eidsvold, Eidsvold East, Eidsvold West, Grosvenor, Malmoe, Wuruma Dam" },
      { postcode: "4630", district: "Bukali, Cania, Cannindah, Coominglah, Coominglah Forest, Glenleigh, Harrami, Kalpowar, Kapaldo, Langley, Monal, Monto, Mulgildie, Selene, Splinter Creek, Tellebang, Three Moon, Ventnor, Yarrol" },
      { postcode: "4650", district: "Antigua, Bauple, Bauple Forest, Beaver Rock, Boonooroo, Boonooroo Plains, Duckinwilla, Dundathu, Dunmora, Ferney, Glenorchy, Gootchie, Grahams Creek, Granville, Gundiah, Maryborough, Mount Steadman, Mount Urah, Mungar, Netherby, Oakhurst, Owanyilla, Pilerwa, Pioneers Rest, St Helens, Talegalla Weir, Tandora, Teddington, The Dimonds, Thinoomba, Tiaro, Tinana, Tinana South, Tuan Forest, Walkers Point" },
      { postcode: "4655", district: "Booral, Bunya Creek, Dundowran Beach, Eli Waters, Great Sandy Strait, Happy Valley, Hervey Bay, Kawungan, Nikenbah, Pialba, Point Vernon, Scarness, Sunshine Acres, Susan River, Torquay, Urangan, Urraween, Walliebum, Walligan, Wondunna" },
      { postcode: "4659", district: "Beelbi Creek, Burgowan, Burrum Heads, Burrum River, Burrum Town, Howard, Pacific Haven" },
      { postcode: "4660", district: "Abington, Buxton, Cherwell, Childers, Cordalba, Eureka, Goodwood, Gregory River, Horton, Isis Central, Isis River, Kullogum, North Gregory, Promisedland, Woodgate" },
      { postcode: "4662", district: "Torbanlea" },
      { postcode: "4671", district: "Boolboonda, Booyal, Dalysford, Damascus, Delan, Doughboy, Drinan, Duingal, Gaeta, Gin Gin, Good Night, Horse Camp, Kolonga, Lake Monduran, Maroondan, Mcilwraith, Molangul, Monduran, Moolboolaman, Morganville, Mount Perry, Mungy, Nearum, New Moonta, Redhill Farms, Skyring Reserve, St Agnes, St Kilda, Takilberan, Tirroan, Wallaville, Wonbah, Wonbah Forest" },
      { postcode: "4673", district: "Miara, Waterloo, Yandaran" },
      { postcode: "4674", district: "Baffle Creek, Berajondo, Deepwater, Euleilah, Mount Maria, Oyster Creek, Rosedale, Rules Beach, Taunton" },
      { postcode: "4676", district: "Gindoran, Lowmead" },
      { postcode: "4677", district: "Agnes Water, Captain Creek, Colosseum, Eurimbula, Miriam Vale, Mount Tom, Round Hill, Seventeen Seventy" },
      { postcode: "4678", district: "Bororen, Foreshores, Rodds Bay" },
      { postcode: "4680", district: "Barney Point, Benaraby, Boyne Island, Boyne Valley, Boynedale, Builyan, Byellee, Callemondah, Calliope, Clinton, Diglum, Gladstone, Glen Eden, Heron Island, Iveragh, Kin Kora, Kirkwood, Mount Alma, New Auckland, O Connell, River Ranch, South Gladstone, South Trees, Sun Valley, Tablelands, Tannum Sands, Taragoola, Telina, Toolooa, Ubobo, West Gladstone, West Stowe, Wooderson" },
      { postcode: "4694", district: "Aldoga, Targinie, Yarwun" },
      { postcode: "4695", district: "Bracewell, Darts Creek, East End, Machine Creek, Mount Larcom, The Narrows" },
      { postcode: "4697", district: "Raglan" },
      { postcode: "4699", district: "Bajool, Port Alma" },
      { postcode: "4700", district: "Allenstown, Fairy Bower, Great Keppel Island, Port Curtis, Rockhampton, The Keppels, The Range, Wandal, West Rockhampton" },
      { postcode: "4701", district: "Berserker, Central Queensland University, Frenchville, Greenlake, Kawana, Koongal, Limestone Creek, Mount Archer, Nankin, Norman Gardens, North Rockhampton, Park Avenue, Rockyview, Sandringham, The Common" },
      { postcode: "4703", district: "Adelaide Park, Bangalee, Barlows Hill, Barmaryee, Barmoya, Byfield, Causeway Lake, Cobraball, Cooee Bay, Hidden Valley, Inverness, Lake Mary, Lammermoor, Maryvale, Meikleville Hill, Mulambin, Mulara, Pacific Heights, Rosslyn, Stockyard, Tanby, Taranganba, Taroomball, Weerriba, Yeppoon" },
      { postcode: "4704", district: "Wattlebank, Yaamba" },
      { postcode: "4705", district: "Clarke Creek, Lotus Creek, Mackenzie River, Marlborough, Mount Gardiner" },
      { postcode: "4706", district: "Ogmore" },
      { postcode: "4707", district: "Collaroy, St Lawrence, The Percy Group" },
      { postcode: "4709", district: "Tieri" },
      { postcode: "4710", district: "Emu Park, Zilzie" },
      { postcode: "4711", district: "Glendale, Glenlee" },
      { postcode: "4712", district: "Duaringa" },
      { postcode: "4713", district: "Woorabinda" },
      { postcode: "4714", district: "Baree, Boulder Creek, Fletcher Creek, Hamilton Creek, Horse Creek, Johnsons Hill, Leydens Hill, Limestone, Moongan, Mount Morgan, Nine Mile Creek, Oakey Creek, The Mine, Trotter Creek, Walmul, Wura" },
      { postcode: "4715", district: "Biloela, Callide, Castle Creek, Dakenba, Dumgree, Greycliffe, Orange Creek, Prospect, Tarramba" },
      { postcode: "4716", district: "Lawgi Dawes, Thangool" },
      { postcode: "4717", district: "Blackwater" },
      { postcode: "4718", district: "Bauhinia, Dromedary, Kianga, Moura, Mungabunda, Oombabeer, Rhydding, Roundstone, Warnoah" },
      { postcode: "4719", district: "Camboon, Cracow, Glenmoral, Isla, Lonesome Creek, Theodore" },
      { postcode: "4720", district: "Emerald" },
      { postcode: "4721", district: "Argyll, Clermont, Pasha" },
      { postcode: "4722", district: "Springsure" },
      { postcode: "4723", district: "Capella" },
      { postcode: "4724", district: "Alpha" },
      { postcode: "4725", district: "Central West	Barcaldine" },
      { postcode: "4726", district: "Aramac" },
      { postcode: "4727", district: "Central West	Ilfracombe" },
      { postcode: "4728", district: "Jericho" },
      { postcode: "4730", district: "Central West	Camoola, Chorregon, Ernestina, Longreach, Maneroo, Morella, Stonehenge, Tocal, Vergemont" },
      { postcode: "4731", district: "Central West	Isisford" },
      { postcode: "4732", district: "Muttaburra" },
      { postcode: "4733", district: "Central West	Corfield" },
      { postcode: "4735", district: "Central West	Diamantina Lakes, Middleton, Opalton, Winton" },
      { postcode: "4736", district: "Central West	Jundah" },
      { postcode: "4737", district: "Armstrong Beach, Blue Mountain, Freshwater Point, Sarina, Sarina Beach, Sarina Range" },
      { postcode: "4738", district: "Koumala" },
      { postcode: "4739", district: "Carmila" },
      { postcode: "4741", district: "Brampton Island, Coppabella, Daydream Island, Epsom, Eton, Eton North, Eungella Hinterland, Farleigh, Gargett, Hampden, Hazledean, Kinchant Dam, Kuttabul, Lindeman Island, Long Island, Mackay Mc, Mount Charlton, Mount Ossa, Mount Pelion, Owens Creek, Pinnacle, Pleystowe, Seaforth, South Molle" },
      { postcode: "4742", district: "Burton, Eaglefield, Elphinstone, Hail Creek, Kemmis, Mount Britton, Nebo, Oxford, Strathfield, Turrawulla, Valkyrie" },
      { postcode: "4743", district: "Glenden, Suttor" },
      { postcode: "4744", district: "Moranbah" },
      { postcode: "4745", district: "Dysart" },
      { postcode: "4746", district: "May Downs, Middlemount" },
      { postcode: "4750", district: "Bucasia, Shoal Point" },
      { postcode: "4751", district: "Greenmount, Victoria Plains, Walkerston" },
      { postcode: "4753", district: "Devereux Creek, Marian" },
      { postcode: "4754", district: "Benholme, Dows Creek, Mia Mia, Mirani, Mount Martin, Pinevale, Septimus" },
      { postcode: "4756", district: "Finch Hatton, Netherdale" },
      { postcode: "4757", district: "Broken River, Crediton, Dalrymple Heights, Eungella, Eungella Dam" },
      { postcode: "4798", district: "Calen, Mentmore" },
      { postcode: "4799", district: "Bloomsbury" },
      { postcode: "4800", district: "Andromache, Brandy Creek, Breadalbane, Cape Conway, Cape Gloucester, Conway Beach, Crystal Brook, Dittmer, Foxdale, Glen Isla, Goorganga Creek, Goorganga Plains, Gregory River, Gunyarra, Hamilton Plains, Hideaway Bay, Kelsey Creek, Laguna Quays, Lake Proserpine, Lethebrook, Mount Pluto, Myrtlevale, Palm Grove, Pauls Pocket, Preston, Proserpine, Silver Creek, Sugarloaf, Thoopara, Wilson Beach" },
      { postcode: "4801", district: "Hayman Island" },
      { postcode: "4802", district: "Airlie Beach, Cannonvale, Flametree, Mandalay, Mount Rooper, Shute Harbour, Whitsundays, Woodwark" },
      { postcode: "4803", district: "Hamilton Island" },
      { postcode: "4804", district: "Collinsville, Mount Coolon, Mount Wyatt, Newlands, Springlands" },
      { postcode: "4805", district: "Northern	Bogie, Bowen, Guthalungra, Merinda, Queens Beach" },
      { postcode: "4806", district: "Northern	Carstairs, Fredericksfield, Home Hill, Inkerman, Kirknie, Osborne, Rangemore, Wangaratta, Wunjunga" },
      { postcode: "4807", district: "Northern	Airdmillan, Airville, Alva, Ayr, Clare, Dalbeg, Eight Mile Creek, Jarvisfield, Mcdesme, Millaroo, Mona Park, Mount Kelly, Mulgrave, Parkside, Swans Lagoon" },
      { postcode: "4808", district: "Northern	Brandon, Colevale" },
      { postcode: "4809", district: "Northern	Barratta, Cromarty, Giru, Horseshoe Lagoon, Jerona, Mount Surround, Shirbourne, Upper Haughton" },
      { postcode: "4810", district: "Northern	Belgian Gardens, Castle Hill, North Ward, Pallarenda, Railway Estate, Rowes Bay, Shelly Beach, South Townsville, Town Common, Townsville, West End" },
      { postcode: "4811", district: "Northern	Cluden, Idalia, James Cook University, Oak Valley, Oonoonba, Roseneath, Stuart, Wulguru" },
      { postcode: "4812", district: "Northern	Currajong, Gulliver, Hermit Park, Hyde Park, Mundingburra, Mysterton, Pimlico, Rosslea" },
      { postcode: "4813", district: "Northern	Townsville Milpo" },
      { postcode: "4814", district: "Northern	Aitkenvale, Annandale, Cranbrook, Douglas, Garbutt, Heatley, Mount Louisa, Murray, Vincent" },
      { postcode: "4815", district: "Northern	Condon, Kelso, Rasmussen" },
      { postcode: "4816", district: "Northern	Alligator Creek, Barringha, Brookhill, Cungulla, Greenvale, Hidden Valley, Homestead, Julago, Kennedy, Macrossan, Mingela, Mutarnee, Nelia, Nome, Palm Island, Paluma, Pentland, Prairie, Ravenswood, Rollingstone, Ross River, Sellheim, Torrens Creek, Woodstock" },
      { postcode: "4817", district: "Northern	Alice River, Bohle Plains, Hervey Range, Kirwan, Thuringowa Central" },
      { postcode: "4818", district: "Northern	Black River, Bluewater, Bluewater Park, Bohle, Bushland Beach, Deeragun, Mount St John, Saunders Beach, Toolakea, Yabulu" },
      { postcode: "4819", district: "Northern	Arcadia, Horseshoe Bay, Magnetic Island, Nelly Bay, Picnic Bay, West Point" },
      { postcode: "4820", district: "Northern	Alabama Hill, Charters Towers, Columbia, Grand Secret, Lissner, Millchester, Mosman Park, Queenton, Richmond Hill, Toll, Towers Hill" },
      { postcode: "4821", district: "Northern	Hughenden, Stamford, Richmond" },
      { postcode: "4822", district: "North West	Albion, Burleigh" },
      { postcode: "4823", district: "North West	Julia Creek, Kynuna, Mckinlay, Warburton" },
      { postcode: "4824", district: "North West	Cloncurry, Oorindi" },
      { postcode: "4825", district: "North West	Breakaway, Buckingham, Carrandotta, Dajarra, Fisher, Georgina, Happy Valley, Healy, Menzies, Mica Creek, Miles End, Mornington, Mount Isa, Parkside, Pioneer, Piturie, Ryan, Soldiers Hill, Sunset, The Gap, The Monument, Townview, Waverley, Winston" },
      { postcode: "4828", district: "North West	Camooweal" },
      { postcode: "4829", district: "Central West	Amaroo, Bedourie, Boulia, Min Min, Sturt, Toko, Warenda, Wills" },
      { postcode: "4830", district: "North West	Burketown, Doomadgee" },
      { postcode: "4849", district: "Northern	Cardwell" },
      { postcode: "4850", district: "Northern	Abergowrie, Allingham, Gairloch, Halifax, Hawkins Creek, Ingham, Lucinda, Macknade, Mount Fox, Taylors Beach, Upper Stone, Victoria Plantation" },
      { postcode: "4852", district: "Bingil Bay, Djiru, Garners Beach, Midgeree Bar, Mission Beach, Wongaling Beach" },
      { postcode: "4854", district: "Cardstone, Euramo, Murray Upper, Tully" },
      { postcode: "4855", district: "Daveson, El Arish, Friday Pocket, Granadilla, Jaffa, Maadi, Maria Creeks, Shell Pocket" },
      { postcode: "4856", district: "Goolboo, Mccutcheon, No 5 Branch, Silkwood, Silkwood" },
      { postcode: "4857", district: "Silkwood East" },
      { postcode: "4858", district: "Comoon Loop, Etty Bay, Martyville, Mourilyan, Mourilyan Harbour, New Harbourline" },
      { postcode: "4859", district: "No 6 Branch, South Johnstone" },
      { postcode: "4860", district: "Bamboo Creek, Belvedere, Coconuts, Cooroo Lands, Coorumba, Coquette Point, Cullinane, Daradgee, East Innisfail, East Palmerston, Eaton, Eubenangee, Fitzgerald Creek, Flying Fish Point, Garradunga, Goondi, Goondi Bend, Goondi Hill, Hudson, Innisfail, Innisfail Estate, Jubilee Heights, Mighell, Mundoo, Nerada, Njatjan, O Briens Hill, Palmerston, Pin Gin Hill, South Innisfail, Stoters Hill, Sundown, Upper Daradgee, Vasa Views, Wanjuru, Webb, Wooroonooran" },
      { postcode: "4861", district: "Babinda, Bartle Frere, East Russell" },
      { postcode: "4865", district: "Goldsborough, Gordonvale, Kamma" },
      { postcode: "4868", district: "Bayview Heights, Mount Sheridan, White Rock, Woree" },
      { postcode: "4869", district: "Bentley Park, Edmonton, Mount Peter, Wrights Creek" },
      { postcode: "4870", district: "Aeroglen, Brinsmead, Bungalow, Cairns, Cairns North, Cairns Orchid Plaza, Earlville, Edge Hill, Freshwater, Kamerunga, Kanimbla, Manoora, Manunda, Martynvale, Mooroobool, Parramatta Park, Redlynch, Stratford, Westcourt, Whitfield" },
      { postcode: "4872", district: "Barrine, Danbulla, Dimbulah, Glen Ruth, Gunnawarra, Innot Hot Springs, Kairi, Kirrama, Koombooloomba, Lake Tinaroo, Minnamoolka, Mount Garnet, Mutchilba, Silver Valley, Tinaroo, Wairuna, Walkamin" },
      { postcode: "4873", district: "Daintree, Diwan, Mossman, Newell, Wonga" },
      { postcode: "4874", district: "Evans Landing, Nanum, Rocky Point, Trunding, Weipa, Weipa Airport" },
      { postcode: "4875", district: "Badu Island, Thursday Island" },
      { postcode: "4876", district: "Bamaga" },
      { postcode: "4877", district: "Port Douglas" },
      { postcode: "4878", district: "Barron, Caravonica, Holloways Beach, Machans Beach, Smithfield, Yorkeys Knob" },
      { postcode: "4879", district: "Clifton Beach, Ellis Beach, Kewarra Beach, Palm Cove, Trinity Beach, Trinity Park" },
      { postcode: "4880", district: "Mareeba" },
      { postcode: "4881", district: "Kuranda" },
      { postcode: "4882", district: "Tolga" },
      { postcode: "4883", district: "Atherton, Carrington, East Barron, Upper Barron, Wongabel" },
      { postcode: "4884", district: "Yungaburra" },
      { postcode: "4885", district: "Malanda" },
      { postcode: "4886", district: "Millaa Millaa" },
      { postcode: "4887", district: "Herberton, Irvinebank, Moomin, Watsonville, Wondecla" },
      { postcode: "4888", district: "Evelyn, Kaban, Millstream, Ravenshoe, Tumoulin" },
      { postcode: "4890", district: "North West	Normanton" },
      { postcode: "4891", district: "North West	Karumba" },
      { postcode: "4895", district: "Cooktown" },
      { postcode: "9726", district: "Gold Coast" },
    ],
    crashes: undefined,
    crashesCount: undefined
  },
  actions: {
    ...load(require.context("./actions", false, /\.js$/))
  },
  mutations: {
    ...load(require.context('./mutations', false, /\.js$/))
  }
};